# Generated by Django 4.1 on 2022-08-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizzas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topping",
            name="name",
            field=models.TextField(),
        ),
    ]
